### ISSUE TITLE
Typescript optional property is hard to see with Tree-sitter highlighting enabled

### ISSUE THREAD

**Issue by antoineco** [sainnhe/everforest#144]
Hi @antoineco, in TypeScript, turning Treesitter on and off can cause inconsistencies in the color of the optional property '?', making it difficult to find them. Here are the comparison images:

Treesitter on: 
![image](https://github.com/user-attachments/assets/115af3cf-43b7-4eed-ad61-8a2f883575a5)

Treesitter off: 
![image](https://github.com/user-attachments/assets/0db7a1a9-24da-4a4c-a596-96b9db274048)

Is there a way to maintain good visibility even when Treesitter is turned on?

_Originally posted by @Daydreamer-riri in https://github.com/sainnhe/everforest/issues/128#issuecomment-2287878652_

**Comment by Daydreamer-riri** [comment]
Thank you! And `gruvbox-material` has the same problem.

**Comment by antoineco** [comment]
@Daydreamer-riri the issue should now be fixed on `master`, both in Everforest and Gruvbox Material 👍

**Comment by Daydreamer-riri** [comment]
Hi @antoineco , thanks for such a quick fix.

But I still don't see the highlighted `? ` , my lazyvim tells me that I have upgraded to [11629d7](https://github.com/sainnhe/everforest/commit/11629d7df5129296d0c7e3ace0778cdc1594b0af)

![image](https://github.com/user-attachments/assets/ce671183-5cf6-430a-8ba6-d1d752585afe)

![image](https://github.com/user-attachments/assets/a190a826-e534-4a61-bb5f-dd3229e60cb2)

**Comment by Daydreamer-riri** [comment]
Neovim : 0.10.1

![image](https://github.com/user-attachments/assets/5b6ae173-01e0-4c02-8e80-e52ea83c640c)

**Comment by antoineco** [comment]
Ahh that makes sense, I forgot that typescript had 2 filetypes (`typescript`, `tsx`) 🤦
